project_id: "899362"
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: "/i18n/en.json"
    translation: "/i18n/%locale_with_underscore%.json"
    type: "json"
    update_option: "update_as_unapproved"
